export const UPDATE_SHIFTS = "UPDATE_SHIFTS";

export const ADD_TO_CALENDAR = "ADD_TO_CALENDAR";
export const ADD_MULTIPLE_TO_CALENDAR = "ADD_MULTIPLE_TO_CALENDAR";
export const REMOVE_FROM_CALENDAR = "REMOVE_FROM_CALENDAR";
export const CLEAR_CALENDAR = "CLEAR_CALENDAR";
export const UPDATE_CALENDAR_QUANTITY = "UPDATE_CALENDAR_QUANTITY";
export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";

export const UPDATE_LOCATIONS = "UPDATE_LOCATIONS";
export const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";
